### ISSUE TITLE
Demo refactoring

### ISSUE THREAD

**Issue by abojchevski** [Rostlab/nalaf#124]
* [x] Enable for demo_predict to work with provided PMIDs
* [x] When printing proteins use "GGP" stands for "Gene or Gene Protein"
* [x] Always print the relations even in color mode
* [x] Update Readme

* [x] separate ANNOTATIONS and RELATIONS with a double new line
* [ ]  change to to GNormPlusGeneTagger().tag(dataset, uniprot=True)

**Comment by jmcejuela** [comment]
For what I can tell, this was done already
