### ISSUE TITLE
Tokenizer non- ascii chars

### ISSUE THREAD

**Issue by abojchevski** [Rostlab/nalaf#157]
From looking at the learned state features by the CRF model, it appreas that some non-ascii characters might have a big impact (for example Δ). Our current tokenizer does not separate them into separate tokens so the model ends up learning bunch of over-fitted specific weights.
Therefore:
* [x] Separate non-ascii chars into their own tokens
* [x] Compare performance

**Comment by jmcejuela** [comment]
Really? Are there so many of those chars?

I doubt it ?

**Comment by abojchevski** [comment]
with the old tokenizer among the 25 highest learned weights were features such as:
* word[0]=ΔSOMETHING   ===> B-e_2
* word[0]=ΔSOMETHING_ELSE ===> B-e_2
* etc...

so far experiments did not show a big differences, in any case i think separating these chars into their own tokens makes sense from a consistency point of view at least

since for example:
* ΔA000B ----  [ΔA, 000, B] (with old) and [Δ, A, 000, B] (with new)
* Δ/Δ ----- [Δ/, Δ] (with old) and [Δ, /, Δ] (with new)

**Comment by jmcejuela** [comment]
Yes, for consistency reasons, I agree in splitting
