### ISSUE TITLE
Example script doesn't annotate mutations (correct?)

### ISSUE THREAD

**Issue by jmcejuela** [Rostlab/nalaf#160]
When I run:

```shell
python example_annotate.py -c /usr/local/bin/ -p 15878741 12625412
```

Only proteins are annotated. Is this the expected behavior or should also the default mutation mentions recognizer kick in ?

**Comment by abojchevski** [comment]
It was supposed to.... BUT.... We forgot that the mutation specific features are in nala, so we won't be able to generate those features, therefore we wont be able to use the default_model and predict mutations.
So... the answer is yes. Only proteins will be recognized.

**Comment by jmcejuela** [comment]
Nothing to do. Would be nice to have a better default sample in nalaf, but anyway
