### ISSUE TITLE
General list of tasks of merging nalaf, nala, relna

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/nalaf#162]
- [x] We merge nalaf / split branch into develop
- [x] We merge ashish branch into develop
- [x] We make sure that relna depends on develop branch of nalaf
* ~~#151 : Move bootstrapping to nalaf as it is (later we gradually move things)~~
- ~~#155 : Leave Mutation constants in nalaf but mark as deprecated & in nalaf recreate the constants and use them from nala only~~
- [x] Rename in nalaf default_model to example_entity_moel
- ~~#163 Make nalaf depend on textblob (nltk)~~
- ~~#163 Maybe/Someday make nalaf use and depend on spacy rather than textblob~~
- ~~#164 Replace relna relations.py in nalaf — Move to relations.py to nalaf: EdgeFeatureGenerator, TokenFeatureGenerator, NamedEntityCountFeatureGenerator, BagOfWords, StemmedBag, SentenceFeature, WOrlfFilter~~
- ~~#165 Move Document Level evaluator to nalaf~~
- ~~#166 Move the standard error and deviation to evaluators~~ (SE not calculated for docRelationsEvaluator at the moment)
- ~~#166 nala team will make the standard error component a general one~~
- ~~[ ] Remove GNormPlusTagger from taggers.py (doesn't belong to nalaf really or otherwise put into separated file)~~ --> **No priority**
- ~~[ ] Rename taggers.py to annotators.py~~ > #171
- ~~[ ] (Juanmi) Make StubSameSentenceRelationExtractor general for list of entities~~ #172
- ~~[ ] Remove SameSentence stub from nala~~ already done
- ~~#77 ~~Make PostProcessor & PreProcessor subclasses of Annotator and have that in nalaf~~
- [x] Remove edges.py from relna
- ~~[ ] move label_edges to a preprocessing file (in nalaf) to labelers.py~~ #173
- ~~[ ] (Juanmi) Rename all functions & variables of annotation to entity (like pred_annotations)~~ #174
- ~~[ ] Merge form_pred_relations from ashish branch to nalaf~~ **DID NOT FOUND THIS**
- ~~[ ] Merge fold with dev & test from ashish branch to nalaf~~ **DID NOT FOUND THIS**
- [x] Merge ashish branch list of parse trees to Part class and write down comment that this could be perhaps too specific and perhaps be removed from here
- ~~[ ] Merge ashish entity as a list of tokens to nalaf~~ #167 
- ~~[ ] Move edge / toke score-like features from ashish to features in nalaf~~ #170 and #164 
- [x] Put comment down in Entity head to specify that this is not the first token, just the head of the entity as declared by parsing
- ~~[ ] Move Dataset_pipelines.py class make it implement Annotator and move it to annotators.py~~ **No priority**
- ~~[ ] In nala rename DocumentSelectorPipeline to DocumentSelectorPMIDPipeline & make subclass of DocumentSelector & Define DocumentSelector interface in nalaf~~ **No priority**
- [x] Move corpora from nalaf to nala

**Comment by jmcejuela** [comment]
https://github.com/Rostlab/nalaf/issues/155

**Comment by jmcejuela** [comment]
Reviewed all items. Left undone or without specific assigned task for those things currently not crucial for nala

**Comment by juanmirocks** [comment]
(SE not calculated for docRelationsEvaluator at the moment)
