### ISSUE TITLE
No module named 'nalaf.domain'

### ISSUE THREAD

**Issue by Gab0** [Rostlab/nalaf#176]
```
>>> import nalaf.domain.bio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nalaf.domain'
```
This may be a python3.6 thing, but `domain` and `bio` folder should have a `__init__.py` file for setup to install this submodule.

**Comment by juanmirocks** [comment]
Thank you @Gab0 for your report!

You are absolutely correct. I added now the __init__.py file -- Can you please verify and tell me that now everything works well ?

Thanks!!

**Comment by Gab0** [comment]
Hey, its working now. Thanks!

**Comment by juanmirocks** [comment]
❤️ awesome. Let me know how I can help you and how you use the software. I cannot fully maintain it at the moment but will do as much as I can.

**Comment by Gab0** [comment]
Nice ^^ actually I need help on how to create a database like that sample_database... I need to highlight a specific set of proteins... Thanks

**Comment by juanmirocks** [comment]
I also manage the tagtog.net text annotation tool. Several users have already used it to [create and share text corpora](https://www.tagtog.net/-corpora). Maybe it helps you. Actually, all the corpora listed there have annotated named entities for proteins/genes.
