### ISSUE TITLE
sudo python3 -m nalaf.download_data

### ISSUE THREAD

**Issue by BuggyLife** [Rostlab/nalaf#178]
sudo python3 -m nalaf.download_data throws the following error.  Is there any thing that could be done to fix this. I know there is a similar issue already opened, but that did not help me.

ImportError: No module named 'spacy.en'

**Comment by juanmirocks** [comment]
Thanks @BuggyLife !

Please check: https://github.com/Rostlab/nalaf/issues/177#issuecomment-430162031 I do not know any other solution but that.

Long term, we will move the APIs and give better support at [tagtog.net](tagtog.net)
